# Generated by Django 3.1.5 on 2022-06-29 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0002_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('History', 'History'), ('Architecture', 'Architecture'), ('Advert', 'Advert'), ('People', 'People'), ('Machine Learning', 'Machine Learning')], default='category', max_length=20),
        ),
    ]
