# Generated by Django 3.1.5 on 2022-06-29 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0003_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='Author name', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='profession',
            field=models.CharField(default='STUDENT POST', max_length=50),
        ),
    ]
