# Generated by Django 3.1.5 on 2022-06-30 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0004_auto_20220629_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(help_text='Enter blog category', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='img'),
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(help_text='Select blog category', to='cms_app.Category'),
        ),
    ]
