# Generated by Django 3.2.14 on 2022-07-29 16:49

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):
    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('blog', '0003_auto_20220713_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True,
                                   help_text='Auto generated from title field and date if not '
                                             'defined.',
                                   max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True,
                                                  help_text='A comma-separated list of tags.',
                                                  through='taggit.TaggedItem', to='taggit.Tag',
                                                  verbose_name='Tags'),
        ),
    ]
