# Generated by Django 3.2.14 on 2022-07-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20220713_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, help_text='Auto generated from title field and dateif not defined.', max_length=100, null=True, unique=True),
        ),
    ]
