# Generated by Django 3.2.14 on 2022-08-02 14:19

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0004_auto_20220729_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='subtitle',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True,
                                                  help_text='A comma-separated list of tags.',
                                                  through='taggit.TaggedItem', to='taggit.Tag',
                                                  verbose_name='Tags'),
        ),
    ]
