# Generated by Django 3.2.14 on 2022-08-02 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogpost_tags'),
        ('blog', '0004_auto_20220729_1649'),
    ]

    operations = [
    ]
