# Generated by Django 3.2.14 on 2022-08-03 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20220802_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, help_text='Auto generated from title field if not defined.', max_length=100, null=True),
        ),
    ]
