# Generated by Django 3.0.8 on 2020-07-29 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapSquare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=252)),
                ('boundaries', models.CharField(max_length=252)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=252)),
                ('front_src', models.CharField(max_length=252)),
                ('back_src', models.CharField(max_length=252)),
                ('alt', models.CharField(max_length=252)),
                ('map_square_obj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.MapSquare')),
            ],
        ),
        migrations.CreateModel(
            name='Photographer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=252)),
                ('type', models.CharField(max_length=252)),
                ('sentiment', models.CharField(max_length=252)),
                ('map_square_obj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.MapSquare')),
                ('photo_ids', models.ManyToManyField(blank=True, to='app.Photo')),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='photographer_obj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Photographer'),
        ),
        migrations.AddField(
            model_name='mapsquare',
            name='photo_ids',
            field=models.ManyToManyField(blank=True, to='app.Photo'),
        ),
    ]
