# Generated by Django 3.2.14 on 2022-07-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='approx_loc',
            field=models.CharField(blank=True, max_length=252, null=True),
        ),
    ]
