# Generated by Django 3.0.8 on 2020-07-30 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='map_square_obj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.MapSquare'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photographer_obj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Photographer'),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='map_square_obj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.MapSquare'),
        ),
    ]
