# Generated by Django 3.2.14 on 2022-07-18 16:14

from django.db import migrations


def permissions_func(apps, _):
    """Adding blog and tag editing permissions"""
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    blog_group, created = Group.objects.get_or_create(name='blog_permissions')

    # blog post permissions
    blogpost_perms = Permission.objects.filter(codename__contains="blogpost")

    # tag permissions
    tag_perms = Permission.objects.filter(codename__contains="tag")

    perms = list(blogpost_perms) + list(tag_perms)

    blog_group.permissions.set(perms)


def reverse_func(apps, _):
    """Undo permissions func"""
    Group = apps.get_model("auth", "Group")
    Group.objects.get(name='blog_permissions').delete()


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(permissions_func, reverse_func)
    ]
