# Generated by Django 3.0.8 on 2020-08-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='photographer_caption_length',
            field=models.IntegerField(null=True),
        ),
    ]
