# Generated by Django 3.0.8 on 2020-07-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='src',
            new_name='back_src',
        ),
        migrations.AddField(
            model_name='photo',
            name='front_src',
            field=models.CharField(default='', max_length=252),
            preserve_default=False,
        ),
    ]
