# Generated by Django 3.0.8 on 2020-10-27 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='sentiment',
            field=models.CharField(max_length=252, null=True),
        ),
        migrations.AddField(
            model_name='photographer',
            name='type',
            field=models.CharField(max_length=252, null=True),
        ),
    ]
