# Generated by Django 3.1.5 on 2022-06-02 14:56

from django.db import transaction, migrations, models


def move_to_booleans(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Photo = apps.get_model('app', 'Photo')
    for photo in Photo.objects.all():
        with transaction.atomic():
            photo.cleaned_src_exists = True if photo.cleaned_src and len(photo.cleaned_src) else \
                False
            photo.front_src_exists = True if photo.front_src and len(photo.front_src) else False
            photo.back_src_exists = True if photo.back_src and len(photo.back_src) else False
            photo.thumbnail_src_exists = True if photo.thumbnail_src and len(photo.thumbnail_src) \
                else False
            photo.save()


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='back_src_exists',
            field=models.BooleanField(default=False),
        ),

        migrations.AddField(
            model_name='photo',
            name='cleaned_src_exists',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photo',
            name='front_src_exists',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photo',
            name='thumbnail_src_exists',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(move_to_booleans)
    ]
