# Generated by Django 3.0.8 on 2020-07-30 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200730_1322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mapsquare',
            old_name='photo_ids',
            new_name='photo_objects',
        ),
        migrations.RenameField(
            model_name='photographer',
            old_name='photo_ids',
            new_name='photo_objects',
        ),
    ]
