# Generated by Django 3.2.14 on 2022-08-03 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_photographer_approx_loc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='back_src',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='cleaned_src',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='front_src',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='thumbnail_src',
        ),
    ]
