# Generated by Django 3.0.8 on 2020-08-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_photo_photographer_caption_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='white_space_ratio_back',
            field=models.DecimalField(decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='white_space_ratio_binder',
            field=models.DecimalField(decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='white_space_ratio_front',
            field=models.DecimalField(decimal_places=4, max_digits=5, null=True),
        ),
    ]
