# Generated by Django 3.0.8 on 2020-07-28 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200728_1534'),
        ('app', '0002_mapsquare'),
    ]

    operations = [
    ]
