# Generated by Django 3.1.5 on 2022-06-02 15:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0002_auto_20220602_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='back_local_path',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='back_src',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='binder_local_path',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='binder_src',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='cleaned_local_path',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='cleaned_src',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='front_local_path',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='front_src',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='thumbnail_src',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='cleaned_src_exists',
            new_name='cleaned_src'
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='front_src_exists',
            new_name='front_src'
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='back_src_exists',
            new_name='back_src'
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='thumbnail_src_exists',
            new_name='thumbnail_src'
        )
    ]
