# Generated by Django 3.2.14 on 2022-07-25 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220718_1614'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cluster',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='photos',
        ),
        migrations.DeleteModel(
            name='CorpusAnalysisResult',
        ),
        migrations.RemoveField(
            model_name='mapsquareanalysisresult',
            name='map_square',
        ),
        migrations.AlterUniqueTogether(
            name='photo',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='photo',
            name='map_square',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='photographer',
        ),
        migrations.RemoveField(
            model_name='photoanalysisresult',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='photographer',
            name='map_square',
        ),
        migrations.RemoveField(
            model_name='photographeranalysisresult',
            name='photographer',
        ),
        migrations.DeleteModel(
            name='Cluster',
        ),
        migrations.DeleteModel(
            name='MapSquare',
        ),
        migrations.DeleteModel(
            name='MapSquareAnalysisResult',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.DeleteModel(
            name='PhotoAnalysisResult',
        ),
        migrations.DeleteModel(
            name='Photographer',
        ),
        migrations.DeleteModel(
            name='PhotographerAnalysisResult',
        ),
    ]
