# Generated by Django 3.0.8 on 2020-07-28 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_merge_20200728_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapsquare',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Photo'),
        ),
    ]
