# Generated by Django 3.0.8 on 2020-08-05 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200730_1818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='map_square_obj',
            new_name='map_square',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='photographer_obj',
            new_name='photographer',
        ),
        migrations.RenameField(
            model_name='photographer',
            old_name='map_square_obj',
            new_name='map_square',
        ),
        migrations.RemoveField(
            model_name='mapsquare',
            name='photo_objects',
        ),
        migrations.RemoveField(
            model_name='photographer',
            name='photo_objects',
        ),
    ]
