# Generated by Django 3.0.8 on 2020-07-28 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200728_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mapsquare',
            old_name='photo',
            new_name='photo_ids',
        ),
    ]
