# Generated by Django 3.0.8 on 2020-07-29 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200728_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='map_square',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.MapSquare'),
        ),
        migrations.CreateModel(
            name='Photographer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=252)),
                ('type', models.CharField(max_length=252)),
                ('sentiment', models.CharField(max_length=252)),
                ('map_square', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.MapSquare')),
                ('photo_ids', models.ManyToManyField(blank=True, to='app.Photo')),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='photographer_obj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Photographer'),
        ),
    ]
