# Generated by Django 3.0.8 on 2020-07-29 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200729_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='photographer_obj',
        ),
    ]
