# Generated by Django 3.0.8 on 2020-07-29 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_photo_photographer_obj'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='photographer_obj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Photographer'),
        ),
    ]
