# Generated by Django 3.0.8 on 2020-07-29 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_photo_photographer_obj'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='map_square',
            new_name='map_square_id',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='photographer_obj',
            new_name='photographer_id',
        ),
    ]
