# Generated by Django 3.0.8 on 2020-07-29 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200729_1947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='map_square_id',
            new_name='map_square_obj',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='photographer_id',
            new_name='photographer_obj',
        ),
    ]
