# Generated by Django 3.0.8 on 2020-07-29 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200729_1956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photographer',
            old_name='map_square',
            new_name='map_square_obj',
        ),
    ]
