name: CI

on:
    push:
        branches:
        - master
        - '*_CI'  # run on branches suffixed with _CI
    pull_request:
        branches:
        - '*'

jobs:
  ##############################################################################
  # Python jobs
  ##############################################################################
  backend_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.8'
        architecture: 'x64'
    - name: Install Python packages and Ubuntu dependencies
      run: |
        pip install -r requirements.txt
        sudo apt install tesseract-ocr
    - name: Cache YOLO weights
      id: cache-yolo-weights
      uses: actions/cache@v2
      with:
          path: ./backend/app/analysis/yolo_files/yolov3.weights
          key: yolo-weights-cache
    - name: Download YOLO weights
      if: steps.cache-yolo-weights.outputs.cache-hit != 'true'
      run: ./.github/scripts/download_yolo_weights.sh
    - name: Run Django tests
      run: |
        cd backend
        python manage.py migrate
        python manage.py test

  python_linters:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x64'
    - name: Install Python packages
      run: |
        pip install -r requirements.txt
        pip install pylint
    - name: Run pylint on backend/
      run: pylint backend/


  ##############################################################################
  # JS jobs
  ##############################################################################

  js_linters:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install frontend deps and eslint
      run: |
        cd frontend
        npm ci
    - name: Run eslint on frontend/src
      run: |
        cd frontend
        ./node_modules/.bin/eslint --max-warnings 0 src

  frontend_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install frontend deps
      run: |
        cd frontend
        npm ci
    - name: Run frontend tests
      run: |
        cd frontend
        CI=true npm run test
